### ISSUE TITLE
onContentHeightChange is not getting called after rowHeightGetter returns new value

### ISSUE THREAD

**Issue by stulees** [schrodinger/fixed-data-table-2#25]
Experiencing this exact issue https://github.com/facebook/fixed-data-table/issues/292 in this repo also. 
## Expected Behavior

`onContentHeightChange` should always get called if any of the rows grew in height
## Current Behavior

The first time `rowHeightGetter` is called it always returns the `rowHeight` value because the rows haven't been rendered yet. Once the rows have been rendered it gets called again and the row height updates (there's about a 500ms delay however) but `onContentHeightChange` does not get called again, and so if any of the rows grew in height, the table cuts them off at the bottom.
## Context

Trying to implement dynamic row heights based on cell values and have the table update its height appropriately
## Your Environment

fixed-data-table-2 0.6.6
react 0.14.8
react-dom 0.14.8

**Comment by KamranAsif** [comment]
Theres definitely a bug with the ```onContentHeightChange``` callback, but it seems to fire half the time.

I'm able to repo it with this fiddle: https://jsfiddle.net/9g7nn77f/
It looks like _reportContentHeight is using stale state data. After the rows are rendered, the scrollHelper values are change but its not reflected in the state yet.

We may need to add a callback to scrollHelper to force a state update when it sees its values change

**Comment by stulees** [comment]
@KamranAsif Thanks for investigating and confirming the issue. Will you be self assigning this bug?  If so, do you have an idea of when a PR for the fix will be ready?

**Comment by KamranAsif** [comment]
Hey, 

I usually work on these issues if 
1. My company sees value in fixing them (for our own application) and assigns them in sprint
2. The fix is easy/interesting/fun and I'll work on it in my free time.

We currently don't use ```onContentHeightChange```, but we have a plan to use dynamic row heights. I believe this bug is the same as https://github.com/schrodinger/fixed-data-table-2/issues/9 so it may get solved as a side effect.

That being said, I don't think we are switching to dynamic row heights anytime soon, and this is a pretty nasty bug to work on. 

I think @burakcan mentioned he might have some avaiable time?

**Comment by wcjordan** [comment]
I discussed this some with Kam.  Our main reason for holding out on this is we plan to fix it with a bigger / more aggressive set of changes to the row height system.  As such we're starting a discussion for how the row height system should be rewritten and will target the change for a minor release bump (0.7.0).  We're sorry for the delays, but we hope to address the issue sometime in the next few months.

**Comment by stulees** [comment]
Thanks for the info. We'll await the 0.7 release for the fix then, appreciate your efforts!

**Comment by KamranAsif** [comment]
@stulees FYI, we switched 0.7 release to be with the new babel compiler. This change will be part of 0.8 now

**Comment by stulees** [comment]
@KamranAsif Okay thanks

**Comment by donnapep** [comment]
@KamranAsif Any idea when the 0.8 release will be coming out that addresses this issue?

**Comment by KamranAsif** [comment]
@donnapep No idea. The migration is going to take a while, and we haven't prioritized it at work.

**Comment by stulees** [comment]
@KamranAsif Any update on the fix and/or 0.8 release for this issue? If not sure, is there a known workaround worth implementing?

**Comment by amit1911** [comment]
Any update on this? This is really causing problems for me. I might have to change my table library just because of this issue which will be really time consuming as my table is quite complex and requires features like 'column reordering', 'fixed columns', 'variable heights', 'horizontal scrolling', etc. Is there any workaround? If nothing, then I am thinking of trying out react-virtualized as that seems to be quite popular. If someone has any suggestions, then please let me know.

**Comment by wcjordan** [comment]
The redux migration release (v1.0.0 previously discussed as 0.8) will address this, and it's on the last mile, but probably won't be released for a month or 2.  We need to do many bug fixes & some more testing and deal with a few ugly merges.  But no major work still remaining.  

You could try the v0.8.0-beta branch and start filing bugs from it if it's urgent.  We may be a bit slower to fix things there, but we will accept PRs.

**Comment by amit1911** [comment]
But this issue is not yet fixed in v0.8.0-beta as well. How complicated is this issue? Is there anything I can do to fix this issue? I really need a fix for this

**Comment by wcjordan** [comment]
I think that's somewhat unknown.  State management and caching of row heights is relatively tricky, but should be much easier to follow on the v0.8.0-beta branch.

@KamranAsif may be able to give details on his thoughts on fixing and where to look.

**Comment by KamranAsif** [comment]
Hmm I'll try and fix the height calculation tonight in 0.8 branch (maybe we should call it redux branch now)

In theory 8.0 _should_ be stable; although it might be _slightly_ slower because we haven't done a performance optimization run on it yet. But at least we can get some testing on it.

**Comment by amit1911** [comment]
Any update on this?

**Comment by KamranAsif** [comment]
Hey,

I gave this a shot and it's significantly more difficult that I thought. I'm going to do a rewrite; should have something up by Monday

**Comment by amit1911** [comment]
Ohh okay. Thanks a lot.

**Comment by amit1911** [comment]
hey Kamran, were you able to fix this issue? So sorry for continuously bugging you on this.

**Comment by amit1911** [comment]
@KamranAsif still no update on this?

**Comment by ardok** [comment]
Any updates on this?

**Comment by wcjordan** [comment]
For anyone looking for a work around, you can use the @amit1911's PR branch #185 

It comes with a performance hit, but should be a viable work around until we can get a beta out that fixes this.

**Comment by wcjordan** [comment]
Does anyone have a good toy reproduction of this issue?  I have a [branch up in PR](https://github.com/schrodinger/fixed-data-table-2/pull/192), which I believe may fix the issue or make it easy to fix.

**Comment by MichelleChen711** [comment]
Hello, any updates on when the fix will be completed?

**Comment by wcjordan** [comment]
I think this is fixed with the v2.0-merge_master branch, but still need some documentation and perf testing as well as fixing some unit tests.  Do you want check that out and see if it fixes the issue you're having?

If it does, I'll hopefully have a beta out in a week or so.

**Comment by MichelleChen711** [comment]
Ok, I'll try it and let you know. Thanks!

**Comment by MichelleChen711** [comment]
We're having trouble installing it because `npm install git+...` doesn't include the `internal` directory, which `main.js` imports.

We also can't run `npm run build-npm` within the `node_modules/fixed-data-table-2` folder because `build_helpers` is in the `.npmignore` 😅 

Lastly, we tried running `git clone` on this repo, checking it to this branch, running `npm run build-dist && npm run build-npm` and we still ran into this error: `Could not resolve './reselect' from /node_modules/fixed-data-table-2/internal/availableViewportWidth.js`.

Any advice?

**Comment by quixotically** [comment]
Hello @MichelleChen711 ,

We've had success using yalc https://github.com/whitecolor/yalc to test out development versions of FDT in our company's repo. Yalc is an alternative to npm/yarn link.

To set up yalc: 
Have interested devs install it globally (not in your project's repo), i.e. npm i yalc -g. 
Then, in your FDT repo, do >npm run build-dist && npm run build-npm && yalc publish.

To use your local FDT in your project:
In your project: >yalc add fixed-data-table-2
Then build your project's third party libs.
Now you should be able to see the local FDT (so in your case v2.0-merge_master) in your project!

Just remember to run >yalc remove fixed-data-table-2 in your project once you're done with it, so you don't commit any yalc stuff.

*If you would like to test out your own changes to FDT iteratively, I suggest writing a script that will do the necessary steps (FDT npm build-dist and build-npm commands, publishing to yalc (with --push, important difference!), then building your project's third party libs) to make things easier.

**Comment by wcjordan** [comment]
@MichelleChen711 and anyone else interested in this fix, I've published a beta release which should (fingers crossed) fix this.  Since I don't have a big app reproducing this to test against, I'm hoping some folks from the community can try it out for me.

To use it, set package.json to point to 1.0.0-beta.3 of fixed-data-table-2 or run `yarn add fixed-data-table-2@beta`.

Any help testing anyone can give me would be great.  Thanks!

**Comment by MichelleChen711** [comment]
@wcjordan Hi! I tried 1.0.0-beta.3, but the issue is still there for me.

**Comment by wcjordan** [comment]
Would it be possible to put together a JsFiddle which reproduces the issue?  If so it will be much easier to debug and I can fix before 1.0 goes out.

This fiddle can be used as a template although you'll need to swap the includes to point to the right branch: https://jsfiddle.net/pooh25g7/11/

**Comment by MichelleChen711** [comment]
I was able to reproduce the issue with the original fixed data table import and it was fixed with 1.0.0-beta.3 here https://jsfiddle.net/0r17wart/  However, on my actual project I was apparently not importing 1.0.0-beta.3 correctly. I fixed the import but now I'm getting this: `TypeError: Cannot read property 'VISIBLE' of undefined at scrollbarsVisible` at this line `scrollStateX === _roughHeights.ScrollbarState.VISIBLE`.

**Comment by wcjordan** [comment]
Well that's no good.  How are you bundling the FDT2 with your application?  It seems to work for me in the compiled dist files (both minified & unminified).  But if you are importing into your repo using webpack or another bundler, there may be an issue if it doesn't support named ES modules such as
```
export const ScrollbarState = { blah: 'blah' }
```

**Comment by MichelleChen711** [comment]
@wcjordan The problem was with rollup. It's working now with webpack and it fixes the issue! However, having `onHorizontalScroll={() => { return false; }}` as a prop on Table breaks the vertical scrollbar. It doesn't respond to clicking and dragging. Not sure if this is related but I'm also getting ```Warning: `NaN` is an invalid value for the `width` css style property. Check the render method of `FixedDataTableCellGroup`.```

**Comment by wcjordan** [comment]
This is probably an issue w/ the beta.  I'll take a look and see if I can fix in a beta patch.  Thanks

**Comment by wcjordan** [comment]
I've fixed and pushed a 1.0.0-beta.4 which fixes the scroll issue you saw.  Thanks for pointing it out!

**Comment by MichelleChen711** [comment]
Thank you! I'll let you know if I run into other issues.

**Comment by wcjordan** [comment]
This should be fixed w/ the v1.0 release
