### ISSUE TITLE
IOS 11 touch scroll problem

### ISSUE THREAD

**Issue by iwfafe** [schrodinger/fixed-data-table-2#342]
You can see detail in my video: 
https://www.youtube.com/watch?v=nnU98BLLz68

## Expected Behavior
The title Example: Touch scroll could not be "move" when we touch scroll inside table

## Current Behavior
All page container table will be affected by smoothly scroll iOS 11 when we scroll inside data-fixed-table

## Steps to Reproduce (for bugs)
follow my video.

## Your Environment
iOS 11.

**Comment by wcjordan** [comment]
This is caused by https://developers.google.com/web/updates/2017/01/scrolling-intervention (you should also see a warning in the browser console). 

Adding the following CSS to your page should fix the issue:

.fixedDataTableLayout_rowsContainer {
    touch-action: none;
}

I'm happy to accept a PR to add that CSS into the v1 branch, but not v0.8 since it would be a breaking change in behavior.

**Comment by iwfafe** [comment]
Thanks your response quickly! 
But I have try to add your CSS to my page but problem still have. 
I guest because of attribute overflow hidden on this table but I have no idea to fix it.

**Comment by iwfafe** [comment]
I found a solution!
I have removed rubber-band effected on iOS devices! 
Thank you.

**Comment by wcjordan** [comment]
Great!  If you don't mind, could you add some details here in case someone else is looking for a fix in the future?

**Comment by iwfafe** [comment]
I think the root cause is: 
data-fix-table use CSS with attribute: 'overflow:hidden', so on touch device with smoothly scroll (rubber band) it will 'realize' the table and the whole page is a 'not-scroll-block'. That is the reason when you touch and scroll inside the table, rubber band effected appear (plz see detail in my video).

The solution is: remove rubber band effected on touch device by CSS : 'position: fixed' or another solution around the root cause.
